# Import Libraries

In [2]:
import pandas as pd 
import string
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

from sklearn.metrics import accuracy_score

In [3]:
# Download necessary resources
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\AL-
[nltk_data]     MOSTAFA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\AL-
[nltk_data]     MOSTAFA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\AL-
[nltk_data]     MOSTAFA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\AL-
[nltk_data]     MOSTAFA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Preprocessing

In [4]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Lowercase
    text = _
    
    # Tokenize
    tokens = word_tokenize(text)
    
    # Remove stopwords
    tokens = _
    
    # Lemmatization (default noun behavior)
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    
    return ' '.join(tokens)

In [14]:
import re
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|@\w+|#\w+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    return " ".join(tokens)

df["cleaned_text"] = df["text"].apply(preprocess_text)

# Loading data

In [15]:
df = pd.read_csv(r"F:\Projects\Project NLP ,LLMs\sentiment_analysis\sentiment_analysis.csv")
df.head()

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram

In [16]:
# Load dataset (assuming CSV with 'text' and 'sentiment' columns)
df['cleaned_text'] = df['text'].apply(preprocess_text)

In [17]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform,cleaned_text
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter,great day looks like dream
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook,feel sorry miss sea beach
2,2017,8,18,night,Don't angry me,negative,Facebook,angry
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook,attend class listening teachers reading slide ...
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram,want go let go
...,...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter,according quarter families six live poverty
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram,plan spend money going well
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook,uploading bamboozle pictures facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter,congratulations guys finish month early booo
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram,actually wish back tahoe miss

# Splitting data

In [22]:
X = df['sentiment'].values
y = df[['sentiment']].values

X_train_text, X_test_text, y_train_raw, y_test_raw = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# One-Hot-Encoding

In [23]:
encoder = OneHotEncoder(sparse_output=False)
y_train = encoder.fit_transform(y_train_raw)
y_test = encoder.transform(y_test_raw)

In [21]:
# Tokenization and Padding
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train_text) 

X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_test_seq = tokenizer.texts_to_sequences(X_test_text)

max_len = max(len(seq) for seq in X_train_seq)

X_train_padded = pad_sequences(X_train_seq, padding='_', maxlen=max_len)
X_test_padded = pad_sequences(X_test_seq, padding='_', maxlen=max_len)

ValueError: Padding type "_" not understood

# Building Model

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
embedding_dim = _

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len),
    SimpleRNN(256, activation='_'),
    Dense(64, activation='_'),
    Dense(y_train.shape[1], activation='_')
])

model.compile(optimizer='adam',
              loss='_',
              metrics=['accuracy'])

# Training Model

In [ ]:
history = model.fit(
    X_train_padded, y_train,
    epochs=_,
    batch_size=32,
    validation_data=(X_test_padded, y_test)
)

# Model Visualization

In [ ]:
import matplotlib.pyplot as plt

# Accuracy Plot
plt.figure()
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train Accuracy', 'Validation Accuracy'])
plt.show()


# Loss Plot
plt.figure()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train Loss', 'Validation Loss'])
plt.show()